modules/admin/models/Client.php
<?php

namespace app\modules\admin\models;

use Yii;

/**
 * This is the model class for table "client".
 *
 * @property int $id
 * @property string $surname
 * @property string $phone
 * @property string $address
 *
 * @property Objects[] $objects
 */
class Client extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'client';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['surname', 'phone', 'address'], 'required'],
            [['surname'], 'string', 'max' => 100],
            [['phone'], 'string', 'max' => 20],
            [['address'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'surname' => 'ФИО',
            'phone' => 'Номер телефона',
            'address' => 'Адрес',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getObjects()
    {
        return $this->hasMany(Objects::className(), ['id_client' => 'id']);
    }
}

modules/admin/controllers/ClientController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\models\Objects;
use Yii;
use app\modules\admin\models\Client;
use app\modules\admin\models\ClientSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST', 'GET'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?']
                    ]

                ],
            ],
        ];
    }

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $id_client = $id;
        $objects = Objects::find()->where(['id_client' => $id])->all();

        return $this->render('view', [
            'model' => $this->findModel($id),
            'objects' => $objects,
        ]);
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Callback model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {   
        //var_dump($this->findModel($id));
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionCreateFromCall($surname, $phone)
    {
        $model = new Client();
        //var_dump($surname);
        //var_dump($phone);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('add-from-call', [
            'model' => $model,
            'surname' => $surname,
            'phone' => $phone
        ]);
    }
}

modules/admin/controllers/ObjectsController.php
<?php

namespace app\modules\admin\controllers;

use app\models\UploadImage;
use Yii;
use app\modules\admin\models\Objects;
use app\modules\admin\models\ObjectsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ObjectsController implements the CRUD actions for Objects model.
 */
class ObjectsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?']
                    ]

                ],
            ],

        ];
    }

    /**
     * Lists all Objects models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ObjectsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Objects model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Objects model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        //var_dump($id);
        $model = new Objects();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //var_dump($model->image);
                $model->imageBefore = UploadedFile::getInstance($model, 'imageBefore');
                $model->imageAfter = UploadedFile::getInstance($model, 'imageAfter');
                //var_dump($model->image);
                if ($model->imageBefore) {
                    $pathB = Yii::getAlias('@webroot/upload/files').$model->imageBefore->baseName.'.'.$model->imageBefore->extension;
                    $model->imageBefore->saveAs($pathB);
                    $model->attachImage($pathB, true,'before');
                    //$model->image = $model->image->baseName . '.' . $model->imageBefore->extension;
    
                }
                if ($model->imageAfter) {
                    $path = Yii::getAlias('@webroot/upload/files').$model->imageAfter->baseName.'.'.$model->imageAfter->extension;
                    $model->imageAfter->saveAs($path);
                    $model->attachImage($path, true, 'after');
                    //$model->image = $model->image->baseName . '.' . $model->imageBefore->extension;
    
                }
                return $this->redirect(['client/view', 'id' => $model->id_client]);
       }
       return $this->render('create', [
        'model' => $model,
        'id_client' => $id,
        ]);
    }

    /**
     * Updates an existing Objects model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        /*if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);*/

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //var_dump($model->image);
                $model->imageBefore = UploadedFile::getInstance($model, 'imageBefore');
                $model->imageAfter = UploadedFile::getInstance($model, 'imageAfter');
                //var_dump($model->image);
                if ($model->imageBefore) {
                    $path = Yii::getAlias('@webroot/upload/files').$model->imageBefore->baseName.'.'.$model->imageBefore->extension;
                    $model->imageBefore->saveAs($path);
                    $model->attachImage($path);
                    //$model->image = $model->image->baseName . '.' . $model->imageBefore->extension;
    
                }
                if ($model->imageAfter) {
                    $path = Yii::getAlias('@webroot/upload/files').$model->imageAfter->baseName.'.'.$model->imageAfter->extension;
                    $model->imageAfter->saveAs($path);
                    $model->attachImage($path);
                    //$model->image = $model->image->baseName . '.' . $model->imageBefore->extension;
    
                }
                return $this->redirect(['client/view', 'id' => $model->id_client]);


        }
      
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Objects model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        
        $model = $this->findModel($id);
        $model->removeImages();
        $model->delete();

        return $this->redirect(['client/view', 'id' => $model->id_client]);
    }

    /**
     * Finds the Objects model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Objects the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Objects::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


}

modules/admin/views/client/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Client */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="client-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/client/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\ClientSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'surname') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'address') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/client/add-from-call.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Client */
/* @var $form yii\widgets\ActiveForm */

$model->phone = $phone;
$model->surname = $surname;
$this->title = 'Добавить клиента';
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="client-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/client/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Client */

$this->title = 'Добавить клиента';
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="client-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,

    ]) ?>

</div>

modules/admin/views/client/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\ClientSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Клиенты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('<i class="fas fa-plus"></i> Добавить клиента', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'surname',
            'phone',
            'address',


            ['class' => 'yii\grid\ActionColumn'],

        ],
    ]); ?>
</div>

modules/admin/views/client/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Client */

$this->title = 'Редактирование клиента - ' . $model->surname;
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/client/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Client */

$this->title = $model->surname;
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="client-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('<i class="fas fa-pen"></i> Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('<i class="fas fa-plus"></i> Добавить объект', ['objects/create', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('<i class="fas fa-trash-alt"></i> Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить запись?',
                'method' => 'post',
            ],
        ]) ?>


    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'surname',
            'phone',
            'address',
        ],


    ]) ?>

    <h1>Объекты</h1>

    <?php foreach ($objects as $obj): ?>

        <p>
            <?= Html::a('Изменить', \yii\helpers\Url::toRoute(['objects/update', 'id_client' => $obj->id_client, 'id' => $obj->id]), ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Удалить', ['objects/delete', 'id' => $obj->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Вы уверены, что хотите удалить запись?',
                    'method' => 'post',
                ],

            ]) ?>
        </p>

        <?= DetailView::widget([
        'model' => $obj,
        'attributes' => [
            'address',
            'info',
            'service_info',

        ],


    ]) ?>

        <div class="row">
            <div class="col-md-2">
                Фото объекта до
            </div>
            <?php $image = $obj->getImageByName('before'); ?>
            <div class="col-md-10">
                <?= Html::img(Yii::getAlias('@web/upload/photos/').$image->filePath, ['class'=>'img-responsive img-thumbnail', 'style' => 'height: 400px;'])?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                Фото объекта после
            </div>
            <?php $image = $obj->getImageByName('after'); ?>
            <div class="col-md-10">
                <?= Html::img(Yii::getAlias('@web/upload/photos/').$image->filePath, ['class'=>'img-responsive img-thumbnail', 'style' => 'height: 400px;'])?>
            </div>
        </div>

    <?php endforeach; ?>
</div>