controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Callback;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Pages;
use yii\data\Pagination;
use app\models\User;



class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //echo Yii::$app->security->generatePasswordHash('garden-stone');die;
        
        $this->addCallback();

        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays policy page.
     *
     * @return string
     */
    public function actionPolicy()
    {
        return $this->render('policy');
    }


    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

     /**
     * Displays ecommerce page.
     *
     * @return string
     */
    public function actionEcommerce()
    {
        return $this->render('ecommerce');
    }

     /**
     * Displays crm page.
     *
     * @return string
     */
    public function actionCrm()
    {
        return $this->render('crm');
    }

        /**
     * Displays Corporate page.
     *
     * @return string
     */
    public function actionCorporate()
    {
        return $this->render('corporate');
    }
         /**
     * Displays mobile page.
     *
     * @return string
     */
    public function actionMobile()
    {
        return $this->render('mobile');
    }




    public function actionServices()
    {
        // return $this->render('services');
        // выполняем запрос
        $this->addCallback();

        $model = Pages::find()->where(['category' => 'Услуги'])->andWhere(['status' => '1'])->all();

        return $this->render('services', [
            'models' => $model,
        ]);



    }

    public function actionProjects()
    {
        $this->addCallback();

        // return $this->render('services');
        // выполняем запрос
        $models = Pages::find()->where(['category' => 'Проекты'])->andWhere(['status' => '1'])->all();

        return $this->render('projects', [
            'models' => $models,
        ]);



    }
    public function actionStages()
    {
        $this->addCallback();

        // return $this->render('services');
        // выполняем запрос
        $query = Pages::find()->where(['category' => 'Этапы работы'])->andWhere(['status' => '1']);
        // делаем копию выборки
        //var_dump($query);
        $countQuery = clone $query;
        // подключаем класс Pagination, выводим по 10 пунктов на страницу
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'defaultPageSize' => 1]);
        // приводим параметры в ссылке к ЧПУ
        $pages->pageSizeParam = false;

        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        // Передаем данные в представление
        return $this->render('pages', [
            'models' => $models,
            'pages' => $pages,
        ]);



    }
    public function actionAdvantages()
    {
        $this->addCallback();

        // return $this->render('services');
        // выполняем запрос
        $query = Pages::find()->where(['category' => 'Преимущества'])->andWhere(['status' => '1']);
        // делаем копию выборки
        //var_dump($query);
        $countQuery = clone $query;
        // подключаем класс Pagination, выводим по 10 пунктов на страницу
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'defaultPageSize' => 1]);
        // приводим параметры в ссылке к ЧПУ
        $pages->pageSizeParam = false;

        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        // Передаем данные в представление
        return $this->render('pages', [
            'models' => $models,
            'pages' => $pages,
        ]);



    }

    public function actionContacts()
    {
        $this->addCallback();

        // return $this->render('services');
        // выполняем запрос
        $query = Pages::find()->where(['category' => 'Контакты'])->andWhere(['status' => '1']);
        // делаем копию выборки
        //var_dump($query);
        $countQuery = clone $query;
        // подключаем класс Pagination, выводим по 10 пунктов на страницу
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'defaultPageSize' => 1]);
        // приводим параметры в ссылке к ЧПУ
        $pages->pageSizeParam = false;

        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        // Передаем данные в представление
        return $this->render('pages', [
            'models' => $models,
            'pages' => $pages,
        ]);



    }

    private function addCallback(){


        $model = new Callback();
        $model->surname = Yii::$app->request->post('surname');
        $model->phone = Yii::$app->request->post('phone');
        $model->status = Callback::STATUS_NEW;
        if($model->save()){

            Yii::$app->session->setFlash('contactFormSubmitted','message',false);
            return $this->refresh();

        } else {
            //var_dump($model->errors);die;
        }


    }

    public function actionProjectsAbout($id)
    {
        $this->addCallback();

        $model = Pages::find()->where(['id' => $id])->andWhere(['status' => '1'])->one();

        return $this->render('projects_about', [
            'model' => $model,
        ]);

    }


}

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>

<section class="slice py-6 pt-lg-7 pb-lg-8 bg-gradient-primary">
     <img src="/map_contacts.jpg" alt=Image class="img-as-bg">

         <div class="container d-flex align-items-center text-center text-lg-left">
            <div class="col px-0">
               <div class="row row-grid align-items-center">
                  <div class=col-lg-6>
                     <h1 class="h1 text-white text-center text-lg-left my-4">Контакты</h1>
                     <p class="lead text-white text-center text-lg-left opacity-8">Build a beautiful, modern website with flexible Bootstrap components built from scratch.</p>
                     <div class="mt-5 text-center text-lg-left"><a href="#sct-form-contact" data-scroll-to class="btn btn-white btn-lg btn-icon"><span class=btn-inner--text>Напсиать письмо</span></a></div>
                  </div>
               </div>
            </div>
         </div>
      </section>
  <section class="slice slice-lg bg-section-secondary">
         <div class=container>
            <div class=row>
               <div class=col-lg-4>
                  <div class="card text-center hover-translate-y-n10 hover-shadow-lg">
                     <div class="px-5 pb-5">
                        <div class=py-3>
                           
                        </div>
                        <h5 class="">Clients</h5>
                        <p class="mt-2 mb-0">Отдел работы с клиентами<br>пн-пт 10:00-18:00</p>
                        <div class=mt-4>
                            <a href="contact.html#" class=link-underline-primary>
                            hello@estrella.agency</a></div>
                     </div>
                  </div>
               </div>
               <div class=col-lg-4>
                  <div class="card text-center hover-translate-y-n10 hover-shadow-lg">
                     <div class="px-5 pb-5">
                        <div class=py-3>
                        </div>
                        <h5 class="">Support</h5>
                        <p class="mt-2 mb-0">Техническая поддержка действующих клиентов<br>пн-вс 24/7</p>
                        <div class=mt-4><a href="contact.html#" class=link-underline-primary>support@estrella.agency</a></div>
                     </div>
                  </div>
               </div>
               <div class=col-lg-4>
                  <div class="card text-center hover-translate-y-n10 hover-shadow-lg">
                     <div class="px-5 pb-5">
                        <div class=py-3>
                        </div>
                        <h5 class="">Finance</h5>
                        <p class="mt-2 mb-0">Финансовый отдел <br>пн-пт 10:00-16:00</p>
                        <div class=mt-4><a href="contact.html#" class=link-underline-primary>finance@estrella.agency</a></div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <section class="slice slice-lg">
         <div class=container>
            <div class="row row-grid justify-content-between align-items-center">
               <div class=col-lg-5>
                  <h3>308015, Россия, г.Белгород<br>Народный бульвар 70, офис 417</h3>
                  
                  <p class="lead my-4">E: <a href="contact.html#">info@estrella.agency</a><br>T: 8 4722 36 50 21</p>
                  
                  <p><small>Хотите поделиться с нами какой-либо обратной связью, сообщить о технической проблеме или просто задать нам вопрос? Не стесняйтесь обращаться к нам, и мы свяжемся с вами в ближайшее время.</small></p>

               </div>

               <div class=col-lg-6>
<a name="sct-form-contact"></a>
                   <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

       
        

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput()->label('Как вас зовут?') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6])->label('Текст') ?>

                   

                    <div class="form-group">
                        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            

    <?php endif; ?>
               </div>
            </div>
         </div>
      </section>





<style type="text/css">
    nav.navbar.navbar-main.navbar-expand-lg.navbar-dark.bg-black {
        background-color: #fff !important;
    }
    a.nav-link.dropdown-toggle.font-weight-normal {
        color: #222 !important;

    }
    a.nav-link.font-weight-normal {
        color: #222 !important;
        font-size: 14px;
    }
</style>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    
</div>

views/site/pages.php
<div class="main-container" style="margin-top: 85px">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
<?php

// подключаем виджет постраничной разбивки
use yii\widgets\LinkPager;

// проходим цикл по данным модели
foreach ($models as $model) {
    // выводим название организации (пример)
    // echo $model->title;
    echo $model->content;

} 
//var_dump($pages);

// отображаем постраничную разбивку
echo LinkPager::widget([
    'pagination' => $pages,
]); ?>

</div>

views/site/projects.php
<?php


use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
      <section class="slice slice-lg py-7">
         <img src="/projects1.jpg" alt=Image class="img-as-bg">
         <span class="mask bg-gradient-dark opacity-7"></span>
         <div class="container d-flex align-items-center" data-offset-top=#navbar-main>
            <div class="col py-5">
               <div class="row align-items-center justify-content-center">
                  <div class="col-md-7 col-lg-7 text-center">
                     <h1 class="display-4 text-white mb-2">Проекты</h1>
                     <span class="text-white text-sm">projects</span>
                  </div>
               </div>
            </div>
         </div>
      </section>
    
    <section class=border-bottom>
         <div class="container py-3">
            <div class="row align-items-center">
               <div class="col-lg-12 mb-4 mb-lg-0">
                  <ul class=nav>
                     <li class=nav-item><a class="nav-link text- active" href="blog-masonry.html#">Все проекты</a></li>
                     <li class=nav-item><a class="nav-link" href="blog-masonry.html#">eCommerce</a></li>
                     <li class=nav-item><a class=nav-link href="blog-masonry.html#">Landing Page</a></li>
                     <li class=nav-item><a class=nav-link href="blog-masonry.html#">Корпоративные сайты</a></li>
                     <li class=nav-item><a class=nav-link href="blog-masonry.html#">CRM системы</a></li>
                     <li class=nav-item><a class=nav-link href="blog-masonry.html#">Мобильные приложения</a></li>
                     <li class=nav-item><a class=nav-link href="blog-masonry.html#">Дизайн</a></li>
                  </ul>
               </div>
            </div>
         </div>
      </section>

      <section class="slice pt-5 pb-7 bg-section-secondary">
         <div class="container masonry-container">
            <div class="row masonry">
               

               <div class="masonry-item col-xl-4 col-md-6">
                  <div class="card hover-translate-y-n3 hover-shadow-lg overflow-hidden">
                     <div class="position-relative overflow-hidden"><a href="blog-masonry.html#" class=d-block><img alt="Image placeholder" src="/todes-pr.jpg" class=card-img-top></a></div>
                     
                     <div class="card-body position-relative delimiter-bottom">
                        <div class="d-flex align-items-center">
                           <div>
                            <a href="blog-masonry.html#" class="avatar avatar-sm rounded-circle d-inline-block">
                                <img alt="Image placeholder" src="/fav_todes.jpg">
                            </a>
                        </div>
                           <div class="pl-3 col-lg-11"><a href="blog-masonry.html#" class="h6 stretched-link lh-150">Todes - школа танцев</a></div>
                        </div>
                     </div>

                     <div class="pb-0 card-body py-3" style="padding-bottom: 0 !important">
                        <small class="d-block text-sm mb-2">#ecommerce</small> 
                     </div>
                  </div>
               </div>

                <div class="masonry-item col-xl-4 col-md-6">
                  <div class="card hover-translate-y-n3 hover-shadow-lg overflow-hidden">
                     <div class="position-relative overflow-hidden"><a href="blog-masonry.html#" class=d-block><img alt="Image placeholder" src="/bissell.jpg" class=card-img-top></a></div>
                     
                     <div class="card-body position-relative delimiter-bottom">
                        <div class="d-flex align-items-center">
                           <div>
                            <a href="blog-masonry.html#" class="avatar avatar-sm rounded-circle d-inline-block">
                                <img alt="Image placeholder" src="/fav_bissell.jpg">
                            </a>
                        </div>
                           <div class="pl-3 col-lg-11"><a href="blog-masonry.html#" class="h6 stretched-link lh-150">Bissell</a></div>
                        </div>
                     </div>

                     <div class="pb-0 card-body py-3" style="padding-bottom: 0 !important">
                        <small class="d-block text-sm mb-2">#ecommerce</small> 
                     </div>
                  </div>
               </div>

               <div class="masonry-item col-xl-4 col-md-6">
                  <div class="card hover-translate-y-n3 hover-shadow-lg overflow-hidden">
                     <div class="position-relative overflow-hidden"><a href="blog-masonry.html#" class=d-block><img alt="Image placeholder" src="/calipso-pr.jpg" class=card-img-top></a></div>
                     
                     <div class="card-body position-relative delimiter-bottom">
                        <div class="d-flex align-items-center">
                           <div>
                            <a href="blog-masonry.html#" class="avatar avatar-sm rounded-circle d-inline-block">
                                <img alt="Image placeholder" src="/fav_calipso.jpg">
                            </a>
                        </div>
                           <div class="pl-3 col-lg-11"><a href="blog-masonry.html#" class="h6 stretched-link lh-150">Калипсо кофе</a></div>
                        </div>
                     </div>

                     <div class="pb-0 card-body py-3" style="padding-bottom: 0 !important">
                        <small class="d-block text-sm mb-2">#ecommerce</small> 
                     </div>
                  </div>
               </div>



            </div>
            
         </div>
      </section>
      <?php /*
<section class="section-services">
    <div class="main-container">
        <h2> <?= Html::encode($models[0]->category) ?> </h2>
        <div class="row">

            <?php foreach ($models as $model):
                $image = $model->getImage();
            ?>


                <div class="col-lg-4 col-md-6 item">
                    <!--<h3><?//= Html::encode($model->title) ?> </h3>-->
                    <div class="services-images">
                        <?= Html::img(Yii::getAlias('@web/upload/photos/').$image->filePath) ?>
                    </div>
                    <div style="text-align: center">
                    <?= Html::button("<span class='glyphicon glyphicon-plus' aria-hidden='true'>Подробнее</span>",
                    ['class'=>'button',
                        'onclick'=> "window.location.href = '" . \Yii::$app->urlManager->createUrl(['/site/projects-about','id'=>$model->id]) . "';",
                    ]
                    ) ?> 
                    </div>

                </div>

            <?php endforeach; ?>
        </div>


    </div>
</section> */ ?>

<style type="text/css">
    nav.navbar.navbar-main.navbar-expand-lg.navbar-dark.bg-black {
        background-color: #fff !important;
    }
    a.nav-link.dropdown-toggle.font-weight-normal {
        color: #222 !important;

    }
    a.nav-link.font-weight-normal {
        color: #222 !important;
        font-size: 14px;
    }
</style>

views/site/projects_about.php
<?php


use yii\helpers\Html;

/* var_dump($model);
die; */
?>

<div class="main-container" style="margin-top: 50px;">
    <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
    <!--<h2> <?= Html::encode($model->title) ?> </h2>-->
        <?php 
            $image = $model->getImage();
        ?>
        <div class="services-images">
        <?= Html::img(Yii::getAlias('@web/upload/photos/').$image->filePath) ?>
        </div>
        <?php 
                echo $model->content;
        ?>
        <?= Html::button("<span class='glyphicon glyphicon-plus' aria-hidden='true'>Вернуться</span>",
                    ['class'=>'button',
                        'onclick'=> "window.location.href = '" . \Yii::$app->urlManager->createUrl(['/site/projects','id'=>$model->id]) . "';",
                    ]
                ) ?> 
<!--         <button type="button" class="button" data-toggle="modal" data-target="#exampleModalCenter">Подробнее</button> -->
</div>
<div class="col-md-2"></div>
</div>
</div>

views/site/services.php
<?php


use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<section class="slice slice-lg py-7">
         <img src="/news.jpg" alt=Image class="img-as-bg">
         <span class="mask bg-gradient-dark opacity-7"></span>
         <div class="container d-flex align-items-center" data-offset-top=#navbar-main>
            <div class="col py-5">
               <div class="row align-items-center justify-content-center">
                  <div class="col-md-7 col-lg-7 text-center">
                     <h1 class="display-4 text-white mb-2">Новости/блог</h1>
                     <span class="text-white text-sm">Пишем о технологиях, новинках из мира IT</span>
                  </div>
               </div>
            </div>
         </div>
      </section>

      <section class="slice pt-5 pb-7 bg-section-secondary">
         <div class="container masonry-container">
            <div class="row mansory">
                 <?php foreach ($models as $model): 
                $image = $model->getImage();
                //die;
                        ?>
               <div class="masonry-item col-xl-4 col-md-6">
                  <div class="card hover-translate-y-n3 hover-shadow-lg overflow-hidden">
                     <div class="position-relative overflow-hidden"><a href="blog-grid.html#" class=d-block>
                        <?= Html::img(Yii::getAlias('@web/upload/photos/').$image->filePath, ['class' => 'card-img-top', 'style' => 'height: 300px;oveflow: hidden;object-fit: cover;']) ?></a></div>
                     <div class="card-body py-4">
                        <a href="blog-grid.html#" class="h5 stretched-link lh-110"><?= Html::encode($model->title) ?></a>
                        <p class="mt-3 mb-0 lh-130" style="height: 60px;overflow: hidden;"><small><?= Html::encode($model->content) ?></small></p>
                     </div>
                    
                  </div>
               </div>
        <?php endforeach; ?>

               


            </div>
            
         </div>
      </section>



<style type="text/css">
    nav.navbar.navbar-main.navbar-expand-lg.navbar-dark.bg-black {
        background-color: #fff !important;
    }
    a.nav-link.dropdown-toggle.font-weight-normal {
        color: #222 !important;

    }
    a.nav-link.font-weight-normal {
        color: #222 !important;
        font-size: 14px;
    }
</style>s