modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use app\models\LoginForm;
use app\models\User;

use app\modules\admin\models\Callback;
use app\modules\admin\models\CallbackSearch;
use app\modules\admin\models\Client;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */

    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?']
                    ]

                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $searchModel = new CallbackSearch();
        $query = Callback::find()->where(['answer' => 0])->limit(4);
        //var_dump($query);
        $dataProvider =  new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,

        ]);
        $client = Client::find()->all();
        $clientCount = count($client);
        return $this->render('console', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'clientCount' => $clientCount,
        ]);
        //return $this->render('console');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionConsole() {

        $searchModel = new CallbackSearch();
        $query = Callback::find()->where(['answer' => 0])->limit(4);
        //var_dump($query);
        $dataProvider =  new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,

        ]);
        $client = Client::find()->all();
        $clientCount = count($client);
        return $this->render('console', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'clientCount' => $clientCount,
        ]);
    }

    public function actionAddAdmin() {
        $model = User::find()->where(['username' => 'admin'])->one();
        if (empty($model)) {
            $user = new User();
            $user->username = 'admin';
            $user->email = 'mail@mail.ru';
            $user->setPassword('admin');
            $user->generateAuthKey();
            if ($user->save()) {
                echo 'good';
            }
        }
        var_dump($user);
    }

    
}

modules/admin/views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAdminAsset;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;


AppAdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&amp;subset=cyrillic-ext" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="assets/admin.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Url::toRoute(['default/console']),
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);


    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/admin/default/login']];
        
    } else {
        $menuItems = [
            ['label' => 'Консоль', 'url' => ['/admin/default/console']],
            ['label' => 'Клиенты', 'url' => ['/admin/client/index']],
            ['label' => 'Обратный звонок', 'url' => ['/admin/callback/index']],
            ['label' => 'Услуги', 'url' => ['/admin/pages/index-services']],
            ['label' => 'Страницы', 'url' => ['/admin/pages/index-pages']],
            ['label' => 'Проекты', 'url' => ['/admin/pages/index-projects']],
            ['label' => 'Настройки', 'url' => ['/admin/settings/index']],
        ];
        $menuItems[] =  '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Выйти (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
              )  
            . Html::endForm()
            . '</li>';
    }
    
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
            
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'homeLink' => false,
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; КаменьСад <?= date('Y') ?></p>

        <p class="pull-right">Разработано в <a href="https://estrella-studio.ru">Estrella</a></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>